osx_image: xcode9.2
language: objective-c
xcode_project: DebugMan.xcworkspace
script: xcodebuild -project DebugMan.xcworkspace -scheme "DebugMan" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
